name: Skan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    # Check for changes every day at 16:00.
    - cron: '00 16 * * *'

jobs:
  skan:
    name: Skan
    runs-on: ubuntu-latest

    steps:
      - shell: julia --color=yes {0}
        run: 'using Pkg; Pkg.add(; name="Skans", version="1")'

      - shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          using Skans
          repo = GitHubRepo()
          pages = [
              WebPage("http://example.com"),
              WebPage("https://bbc.com")
          ]
          skan!(repo, pages)

